### ISSUE TITLE
Ideia de visualização

### ISSUE THREAD

**Issue by Flaviano-Rodrigues** [DeboraAlmeida/MyLife#1]
Oi! 😃 

Seria interessante se você colocasse este seu repositório hospedado no github(como se fosse um site) pois assim nos conseguiríamos visualizar seu código em ação.

Exemplo: https://flaviano-rodrigues.github.io/Trabalho-Git-e-GitHub/ 

Esse projeto é o primeiro q o roque passou. Ele além de estar [aqui no github como repositório normal](https://github.com/flaviano-rodrigues/trabalho-git-e-github), ele também está hospedado como se fosse um site mesmo

**Comment by DeboraAlmeida** [comment]
Oi! 

Amei sua ideia!! Vou implementar! Obrigada pela dica!
